//! Cross-validation of the Rust codec against the spec bundle's synthetic
//! vectors (`vectors/` + `manifest.json`).
//!
//! These vectors are generated by the reference Python codec and marked
//! `independent_oracle=false` (spec 17 §5): they are regression fixtures,
//! not a correctness proof. The Rust implementation was written from the
//! spec text; agreement here is cross-language confirmation of the byte
//! contracts in specs 03/05/06/07.

use mst2_codec::chunkmap::{ChunkLeaf, ChunkMap};
use mst2_codec::descriptor::ServingDescriptor;
use mst2_codec::metapage::{page_id, EntryKind, Page};
use mst2_codec::treeframe::{parse_frame, parse_stream, Frame};
use serde_json::Value;

const SPEC_ROOT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../Mega_ScorpioFS_MST2_Specs_0.2.1_2026-09-15/mega_scorpio_mst2_specs"
);

fn vectors_dir() -> std::path::PathBuf {
    std::path::Path::new(SPEC_ROOT).join("vectors")
}

fn read(file: &str) -> Vec<u8> {
    std::fs::read(vectors_dir().join(file)).unwrap_or_else(|e| panic!("read {file}: {e}"))
}

fn manifest() -> Value {
    let v: Value =
        serde_json::from_str(&String::from_utf8(read("manifest.json")).unwrap()).unwrap();
    v
}

fn hex_to_32(s: &str) -> [u8; 32] {
    let s = s.strip_prefix("sha256:").unwrap_or(s);
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap();
    }
    out
}

fn sha256_file(bytes: &[u8]) -> [u8; 32] {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().into()
}

fn vector_row(m: &Value, file: &str) -> Value {
    m["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|r| r["file"].as_str() == Some(file))
        .unwrap_or_else(|| panic!("manifest row for {file}"))
        .clone()
}

#[test]
fn mtp2_vectors_parse_reencode_and_page_id() {
    let m = manifest();
    for file in [
        "metadata-empty.bin",
        "metadata-root.bin",
        "metadata-src.bin",
        "metadata-wide-00.bin",
        "metadata-wide-01.bin",
        "metadata-wide-02.bin",
    ] {
        let row = vector_row(&m, file);
        let bytes = read(file);
        assert_eq!(
            sha256_file(&bytes),
            hex_to_32(row["sha256_file"].as_str().unwrap()),
            "{file}: file digest"
        );
        assert_eq!(bytes.len(), row["byte_length"].as_u64().unwrap() as usize);
        let (page, total) = Page::decode(&bytes).unwrap_or_else(|e| panic!("{file}: {e}"));
        // Canonical roundtrip: re-encoding a valid page must be byte-exact.
        let re = page
            .encode()
            .unwrap_or_else(|e| panic!("{file}: reencode {e}"));
        assert_eq!(re, bytes, "{file}: re-encode is not byte-identical");
        // page_id must match the manifest semantic id.
        let pid = page_id(&bytes);
        assert_eq!(
            pid,
            hex_to_32(row["semantic_id"].as_str().unwrap()),
            "{file}: page_id vs semantic_id"
        );
        // root dir (5 entries) and wide dir (140 entries) totals
        if file == "metadata-root.bin" {
            assert_eq!(total, 5);
            match page {
                Page::Leaf { entries } => {
                    let names: Vec<&[u8]> = entries.iter().map(|e| e.name.as_slice()).collect();
                    assert_eq!(
                        names,
                        vec![&b"README.md"[..], b"large.bin", b"link", b"run.sh", b"src"]
                    );
                    let kinds: Vec<EntryKind> = entries.iter().map(|e| e.kind).collect();
                    assert_eq!(
                        kinds,
                        vec![
                            EntryKind::Regular,
                            EntryKind::Regular,
                            EntryKind::Symlink,
                            EntryKind::Executable,
                            EntryKind::Directory
                        ]
                    );
                    // Sizes from the generator.
                    assert_eq!(entries[0].size, 23); // "Hello, fixed snapshot.\n"
                    assert_eq!(entries[3].size, 18); // "#!/bin/sh\necho ok\n"
                    assert_eq!(entries[1].size, 300000); // large.bin
                    assert_eq!(entries[2].size, 10); // "src/lib.rs"
                }
                _ => panic!("root must be a leaf"),
            }
        }
        if file == "metadata-empty.bin" {
            assert_eq!(total, 0);
        }
    }
}

#[test]
fn wide_directory_root_is_branch_with_child_links() {
    let m = manifest();
    let root_id = hex_to_32(m["wide_directory_root"].as_str().unwrap());
    let mut total_by_file: Vec<(&str, [u8; 32])> = Vec::new();
    for file in [
        "metadata-wide-00.bin",
        "metadata-wide-01.bin",
        "metadata-wide-02.bin",
    ] {
        let bytes = read(file);
        let pid = page_id(&bytes);
        total_by_file.push((file, pid));
        if pid == root_id {
            let (page, total) = Page::decode(&bytes).unwrap();
            assert_eq!(total, 140, "wide root must cover 140 entries");
            match page {
                Page::Branch { children, .. } => {
                    // Both child pages must be the other two vector files.
                    let child_ids: Vec<[u8; 32]> =
                        children.iter().map(|c| c.child_page_id).collect();
                    assert_eq!(child_ids.len(), 2);
                    for (_, other) in &total_by_file {
                        if *other != pid {
                            assert!(child_ids.contains(other));
                        }
                    }
                }
                _ => panic!("wide root must be a branch"),
            }
        }
    }
}

#[test]
fn serving_descriptor_vector() {
    let m = manifest();
    let bytes = read("descriptor.bin");
    assert_eq!(
        sha256_file(&bytes),
        hex_to_32(
            vector_row(&m, "descriptor.bin")["sha256_file"]
                .as_str()
                .unwrap()
        )
    );
    let d = ServingDescriptor::decode(&bytes).unwrap();
    assert_eq!(d.scope, "/project/app");
    assert_eq!(
        d.snapshot_id().unwrap(),
        hex_to_32(
            vector_row(&m, "descriptor.bin")["semantic_id"]
                .as_str()
                .unwrap()
        )
    );
    // Generator used instance 11111111-2222-4333-8444-555555555555.
    assert_eq!(d.instance_uuid[0], 0x11);
    assert_eq!(d.instance_uuid[15], 0x55);
    // RFC 4122 version/variant nibbles of that fixture UUID.
    assert_eq!(d.instance_uuid[6] >> 4, 4);
    assert_eq!(d.instance_uuid[8] >> 6, 0b10);
}

#[test]
fn object_stream_vector() {
    let m = manifest();
    let bytes = read("object-stream.bin");
    let frames = parse_stream(&bytes).unwrap();
    assert_eq!(frames.len(), 2);
    match &frames[0] {
        Frame::Object(p) => {
            assert_eq!(p.objects.len(), 2);
            assert_eq!(p.objects[0].1, b"Hello, fixed snapshot.\n");
            assert_eq!(p.objects[1].1, b"#!/bin/sh\necho ok\n");
        }
        _ => panic!("expected OBJECT frame"),
    }
    match &frames[1] {
        Frame::End(e) => {
            assert_eq!(e.request_item_count, 2);
            assert_eq!(e.unique_unit_count, 2);
            assert_eq!(e.logical_bytes, 23 + 18);
            // END request hash = SHA256 of the exact request body bytes.
            let body = read("objects-request-body.json");
            assert_eq!(sha256_file(&body), e.request_body_sha256);
        }
        _ => panic!("expected END frame"),
    }
    // The single OBJECT frame vector must equal the first frame bytes.
    let single = read("object-frame.bin");
    assert_eq!(&bytes[..single.len()], &single[..]);
}

#[test]
fn metadata_stream_vector() {
    let m = manifest();
    let bytes = read("metadata-stream.bin");
    let frames = parse_stream(&bytes).unwrap();
    assert_eq!(frames.len(), 2);
    match &frames[0] {
        Frame::Meta(p) => {
            assert_eq!(p.pages.len(), 1);
            // The page must be the metadata-root vector page.
            assert_eq!(p.pages[0].1, read("metadata-root.bin"));
        }
        _ => panic!("expected META frame"),
    }
    match &frames[1] {
        Frame::End(e) => {
            assert_eq!(e.request_item_count, 1);
            assert_eq!(e.unique_unit_count, 1);
            let body = read("metadata-request-body.json");
            assert_eq!(sha256_file(&body), e.request_body_sha256);
        }
        _ => panic!("expected END frame"),
    }
    let _ = m;
}

#[test]
fn chunk_vector_group() {
    let m = manifest();
    // Single CHUNK frame (stream 21, no END in this vector).
    let frame_bytes = read("chunk-frame.bin");
    let (frame, used) = parse_frame(&frame_bytes).unwrap();
    assert_eq!(used, frame_bytes.len());
    let map_id = match &frame {
        Frame::Chunk(c) => {
            assert_eq!(c.chunk_index, 0);
            assert_eq!(c.chunk_bytes.len(), 300000);
            // Chunk bytes hash to the file content id.
            assert_eq!(sha256_file(&c.chunk_bytes), c.file_content_id);
            c.map_id
        }
        _ => panic!("expected CHUNK frame"),
    };
    // Map descriptor.
    let map_bytes = read("chunk-map.bin");
    let map = ChunkMap::decode(&map_bytes).unwrap();
    assert_eq!(map.map_id(), map_id, "CHUNK frame map_id must bind the map");
    assert_eq!(
        map.map_id(),
        hex_to_32(
            vector_row(&m, "chunk-map.bin")["semantic_id"]
                .as_str()
                .unwrap()
        )
    );
    assert_eq!(map.file_size, 300000);
    assert_eq!(map.chunk_count, 1);
    assert_eq!(map.page_count, 1);
    // Leaf page and Merkle root with a single leaf.
    let leaf_bytes = read("chunk-map-leaf.bin");
    let leaf = ChunkLeaf::decode(&leaf_bytes).unwrap();
    assert_eq!(leaf.page_index, 0);
    assert_eq!(leaf.chunk_sha256.len(), 1);
    assert_eq!(leaf.chunk_sha256[0], map.file_content_id);
    let l0 = leaf.leaf_hash().unwrap();
    assert_eq!(
        l0,
        hex_to_32(
            vector_row(&m, "chunk-map-leaf.bin")["semantic_id"]
                .as_str()
                .unwrap()
        )
    );
    assert_eq!(
        mst2_codec::chunkmap::merkle_root(&[l0]).unwrap(),
        map.pages_root
    );
    // Proof verification for the single-leaf tree (empty proof).
    mst2_codec::chunkmap::verify_leaf(1, 0, l0, &[], map.pages_root).unwrap();
}
